apiVersion: v1
kind: Alert
app: AWS SQS
version: 1.0.0
appVersion:
- 1.0.0
descriptionFile: ALERTS.md
configurations:
- kind: Prometheus
  data: |
    groups:
    - name: AWS-SQS
      rules:
      - alert: HighNumberOfMessagesInQueue
        expr: |
          (aws_sqs_approximate_number_of_messages_delayed_average +
            aws_sqs_approximate_number_of_messages_not_visible_average +
            aws_sqs_approximate_number_of_messages_visible_average)
          > 100
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: High number of messages for a long time in queue {{$labels.dimension_QueueName}}
      - alert: HighLatencyInQueue
        expr: |
          aws_sqs_approximate_age_of_oldest_message_maximum > 300
        for: 30m
        labels:
          severity: page
        annotations:
          summary: High latency in queue {{$labels.dimension_QueueName}}
      - alert: RecurringEmptyReceives
        expr: |
          aws_sqs_number_of_empty_receives_sum > 0
        for: 120m
        labels:
          severity: warning
        annotations:
          summary: Recurring empty receives in queue {{$labels.dimension_QueueName}}
      - alert: MessageReceivedInDeadLetterQueue
        expr: |
          aws_sqs_number_of_messages_sent_sum{dimension_QueueName=~"dead-letter-.+"} > 0
        for: 120m
        labels:
          severity: page
        annotations:
          summary: Message received in dead-letter queue {{$labels.dimension_QueueName}}
