apiVersion: v1
kind: Alert
app: Docker
version: 1.0.0
appVersion:
- 18.09.9
descriptionFile: ALERTS.md
configurations:
- kind: Prometheus
  data: |
    groups:
    - name: Docker-Engine
      rules:
      - alert: BuilderBuildsFailRateTooHigh
        expr: sum(rate(builder_builds_failed_total[5m])) >
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: The build faild rate is too high(instance {{ $labels.instance }})
      - alert: DaemonContainerActionLatencyTooHigh
        expr: histogram_quantile(0.90, rate(engine_daemon_container_actions_seconds_bucket)) > 5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: The the container action {{ $labels.action }} latency is too high for the instance {{ $labels.instance }}
