apiVersion: v1
kind: Alert
app: Windows
version: 1.0.0
appVersion:
- '2016'
- '2019'
descriptionFile: ALERTS.md
configurations:
- kind: Prometheus
  data: |
    groups:
    - name: Windows
      rules:
      - alert: HighCPUUsage
        expr: 100 * sum by (instance) (rate(windows_cpu_time_total{mode != 'idle'}[5m])) / count by (instance) (windows_cpu_core_frequency_mhz) > 95
        for: 15m
        labels:
          severity: page
        annotations:
          summary: High CPU usage in instance {{$labels.instance}}
      - alert: HighPhysicalMemoryUsage
        expr: 100 * (windows_cs_physical_memory_bytes - windows_os_physical_memory_free_bytes) / windows_cs_physical_memory_bytes  > 95
        for: 15m
        labels:
          severity: page
        annotations:
          summary: High physical memory usage in instance {{$labels.instance}}
      - alert: LogicalDiskFull
        expr: 100 * (windows_logical_disk_size_bytes - windows_logical_disk_free_bytes) / windows_logical_disk_size_bytes  > 95
        for: 15m
        labels:
          severity: page
        annotations:
          summary: Disk {{$labels.volume}} full over 95% in instance {{$labels.instance}}
      - alert: UpTimeLessThanOneHour
        expr: time() - windows_system_system_up_time  < 3600
        for: 15m
        labels:
          severity: page
        annotations:
          summary: Up Time of less than 1 hour in instance {{$labels.instance}}
      - alert: HighInboundErrorRate
        expr: 100 * rate(windows_net_packets_received_errors[5m]) / (rate(windows_net_packets_received_errors[5m]) + rate(windows_net_packets_received_total[5m])>0)  > 75
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High inbound network error rate in instance {{$labels.instance}}
      - alert: HighOutboundErrorRate
        expr: 100 * rate(windows_net_packets_outbound_errors[5m]) / (rate(windows_net_packets_outbound_errors[5m]) + rate(windows_net_packets_sent_total[5m])>0)  > 75
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High outbound network error rate in instance {{$labels.instance}}
