apiVersion: v1
kind: Alert
app: AWS EBS
version: 1.0.0
appVersion:
- 1.0.0
descriptionFile: ALERTS.md
configurations:
- kind: Prometheus
  data: |
    groups:
    - name: AWS-EBS
      rules:
      - alert: LowVolumePerformance
        expr: |
          aws_ebs_volume_throughput_percentage_average < 99.9
        for: 10m
        labels:
          severity: page
        annotations:
          summary: The IOPS SSD Performance is under 99.9% in volume {{$labels.dimension_VolumeId}}
      - alert: ZeroVolumeBurstBalance
        expr: |
          aws_ebs_burst_balance_minimum == 0
        for: 30m
        labels:
          severity: page
        annotations:
          summary: The Burst Balance is zero in volume {{$labels.dimension_VolumeId}}
