apiVersion: v1
kind: Alert
app: AWS S3
version: 1.0.0
appVersion:
- 1.0.0
descriptionFile: ALERTS.md
configurations:
- kind: Prometheus
  data: |
    groups:
    - name: AWS-S3
      rules:
      - alert: High4XXErrorRate
        expr: aws_s3_4xx_errors_average > 0.15
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High 4XX error rate on bucket {{$labels.dimension_BucketName}}
      - alert: High5XXErrorRate
        expr: aws_s3_5xx_errors_average > 0.15
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High 5XX error rate on bucket {{$labels.dimension_BucketName}}
      - alert: HighFirstByteLatency
        expr: avg(aws_s3_first_byte_latency_p95) > 250
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High latency on bucket {{$labels.dimension_BucketName}}
