apiVersion: v1
kind: Alert
app: Nginx
version: 1.0.0
appVersion:
- '1.17'
descriptionFile: ALERTS.md
configurations:
- kind: Prometheus
  data: |
    groups:
    - name: Nginx
      rules:
      - alert: NoIntancesUp
        expr: sum by (app)(nginx_up or vector(0)) == 0
        for: 10m
        labels:
          severity: page
        annotations:
          summary: No Nginx instances Up for the app {{$labels.app}}

