apiVersion: v1
kind: Alert
app: AWS Lambda
version: 1.0.0
appVersion:
- 1.0.0
descriptionFile: ALERTS.md
configurations:
- kind: Prometheus
  data: |
    groups:
    - name: AWS-Lambda
      rules:
      - alert: HighFunctionErrorRate
        expr: (aws_lambda_errors_sum / aws_lambda_invocations_sum) > 0.15
        for: 10m
        labels:
          severity: page
        annotations:
          summary: High error rate on function {{$labels.dimension_FunctionName}}
      - alert: ThrottlingFunction
        expr: aws_lambda_throttles_sum  > 0
        for: 10m
        labels:
          severity: page
        annotations:
          summary: Detected throttling in function {{$labels.dimension_FunctionName}}
      - alert: DestinationDeliveryFailures
        expr: aws_lambda_destination_delivery_failures_sum > 0
        for: 10m
        labels:
          severity: page
        annotations:
          summary: Detected destination delivery failures in function {{$labels.dimension_FunctionName}}
      - alert: DeadLetterErrors
        expr: aws_lambda_dead_letter_errors_sum  > 0
        for: 10m
        labels:
          severity: page
        annotations:
          summary: Detected dead-letter queue errors in function {{$labels.dimension_FunctionName}}
      - alert: HighIteratorAge
        expr: aws_lambda_iterator_age_average  > 1000
        for: 10m
        labels:
          severity: page
        annotations:
          summary: Detected high iterator age in function {{$labels.dimension_FunctionName}}
