apiVersion: v1
kind: Alert
app: redis
version: 1.0.0
appVersion:
- 2-6
configurations:
- kind: Prometheus
  data: |
    - alert: RedisLowUptime
      expr: redis_uptime_in_seconds < 3600
      for: 15m
      labels:
        severity: page
      annotations:
        summary: Uptime of less than 1 hour in a redis instance {{$labels.instance}}
    - alert: RedisHighMemoryUsage
      expr: (redis_memory_used_bytes / redis_memory_max_bytes) > 0.85
      for: 15m
      labels:
        severity: page
      annotations:
        summary: High memory usage in instance {{$labels.instance}}
    - alert: RedisHighClientsUsage
      expr: (redis_connected_clients / redis_config_maxclients) > 0.85
      for: 15m
      labels:
        severity: page
      annotations:
        summary: High client connections usage in instance {{$labels.instance}}
    - alert: RedisHighResponseTime
      expr: |
        sum(rate(redis_commands_duration_seconds_total[5m])) /
          sum(rate(redis_commands_processed_total[5m]))
          > 0.250
      for: 10m
      labels:
        severity: page
      annotations:
        summary: Response time over 250ms in instance {{$labels.instance}}
    - alert: RedisHighFragmentationRatio
      expr: fragmentation_ratio > 1.5
      for: 30m
      labels:
        severity: page
      annotations:
        summary: High fragmentation in instance {{$labels.instance}}
    - alert: RedisHighKeysEvictionRatio
      expr: (sum(rate(redis_evicted_keys_total[5m])) / sum(redis_db_keys)) > 0.1
      for: 30m
      labels:
        severity: page
      annotations:
        summary: High keys eviction ratio in instance {{$labels.instance}}
    - alert: RedisRecurrentRejectedConnections
      expr: (rate(redis_rejected_connections_total[5m])) > 0
      for: 15m
      labels:
        severity: page
      annotations:
        summary: High keys eviction ratio in instance {{$labels.instance}}
    - alert: RedisLowHitRatio
      expr: |
        (rate(redis_keyspace_hits_total[5m]) /
          (rate(redis_keyspace_misses_total[5m]) + rate(redis_keyspace_hits_total[5m])))
          < 0.9
      for: 30m
      labels:
        severity: page
      annotations:
        summary: Low keyspace hit ratio in instance {{$labels.instance}}
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "redis_uptime_in_seconds < 3600",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "LowUptime",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 15,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "(redis_memory_used_bytes / redis_memory_max_bytes) > 0.85",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "HighMemoryUsage",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 15,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "(redis_connected_clients / redis_config_maxclients) > 0.85",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "HighClientsUsage",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 15,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "sum(rate(redis_commands_duration_seconds_total[5m])) / \n  sum(rate(redis_commands_processed_total[5m])) \n  > 0.250\n",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "HighResponseTime",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 10,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "fragmentation_ratio > 1.5",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "HighFragmentationRatio",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 30,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "(sum(rate(redis_evicted_keys_total[5m])) / sum(redis_db_keys)) > 0.1",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "HighKeysEvictionRatio",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 30,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "(rate(redis_rejected_connections_total[5m])) > 0",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "RecurrentRejectedConnections",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 15,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
- kind: Sysdig
  data: |-
    {
      "alert": {
        "condition": "(rate(redis_keyspace_hits_total[5m]) / \n  (rate(redis_keyspace_misses_total[5m]) + rate(redis_keyspace_hits_total[5m]))) \n  < 0.9\n",
        "customNotification": {
          "titleTemplate": "{{__alert_name__}} is {{__alert_status__}}",
          "useNewTemplate": false
        },
        "enabled": true,
        "name": "LowHitRatio",
        "rateOfChange": false,
        "reNotify": false,
        "reNotifyMinutes": 30,
        "severity": 4,
        "severityLabel": "LOW",
        "severityLevel": null,
        "timespan": 600000000,
        "type": "PROMETHEUS"
      }
    }
descriptionFile: ALERTS.md
